version: '3'
services:
  a:
    image: docker.jampad.net/sample/recursivecall-go
    deploy:
        replicas: 3
    networks:
      - recursivecallnet

  b:
    image: docker.jampad.net/sample/recursivecall-go
    healthcheck:
      test: ["CMD", "./recursivecall", "check", "a"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
        replicas: 3
    networks:
      - recursivecallnet
      
  c:
    image: docker.jampad.net/sample/recursivecall-go
    healthcheck:
      test: ["CMD", "./recursivecall", "check", "b"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
        replicas: 3
    networks:
      - recursivecallnet
      
  d:
    image: docker.jampad.net/sample/recursivecall-go
    healthcheck:
      test: ["CMD", "./recursivecall", "check", "c"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
        replicas: 3
    networks:
      - recursivecallnet
      
  e:
    image: docker.jampad.net/sample/recursivecall-go
    healthcheck:
      test: ["CMD", "./recursivecall", "check", "d"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
        replicas: 3
    networks:
      - recursivecallnet
      
  f:
    image: docker.jampad.net/sample/recursivecall-go
    healthcheck:
      test: ["CMD", "./recursivecall", "check", "e"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
        replicas: 3
    networks:
      - recursivecallnet
      
  g:
    image: docker.jampad.net/sample/recursivecall-go
    healthcheck:
      test: ["CMD", "./recursivecall", "check", "f"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
        replicas: 3
    networks:
      - recursivecallnet
    ports:
      - "3000:3000"

networks:
  recursivecallnet:
    driver: overlay
    driver_opts:
      encrypted: ""
