apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service.name: a
    application.name: recursivecall-go
  name: a
spec:
  replicas: 3
  selector:
    matchLabels:
      service.name: a
      application.name: recursivecall-go
  template:
    metadata:
      labels:
        service.name: a
        application.name: recursivecall-go
    spec:
      containers:
      - env:
        - name: PROCS
          value: "1"
        image: davidbetz/recursivecall-go
        name: a
        resources: {}
      restartPolicy: Always
status: {}
