apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: d
    application.name: recursivecall-go
  name: d
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service.name: d
