apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service.name: e
    application.name: recursivecall-go
  name: e
spec:
  replicas: 3
  selector:
    matchLabels:
      service.name: e
      application.name: recursivecall-go
  template:
    metadata:
      labels:
        service.name: e
        application.name: recursivecall-go
    spec:
      containers:
      - env:
        - name: PROCS
          value: "1"
        image: davidbetz/recursivecall-go
        livenessProbe:
          exec:
            command:
            - ./recursivecall
            - check
            - d
          failureThreshold: 3
          periodSeconds: 5
          timeoutSeconds: 10
        name: e
        resources: {}
      restartPolicy: Always
status: {}
