apiVersion: v1
kind: Service
metadata:
  labels:
    service.name: g
    application.name: recursivecall-go
  name: g
spec:
  ports:
  - name: "3000"
    port: 3000
    nodePort: 31234
  selector:
    service.name: g
  type: LoadBalancer
